name: flutter_app
description: A new Flutter application.
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^0.4.3
  dio: ^2.1.0
  flutter_redux: ^0.5.0
  date_format: ^1.0.6
  image_picker: ^0.4.0
  custom_radio: ^0.1.2
  flutter_spinkit: "^3.1.0"
  flutter_typeahead: "^1.4.0"
  flutter_easyrefresh: "^1.2.7"
  package_info: "^0.4.0+6"
  flutter_downloader: "1.1.3"
  path_provider: "^0.5.0+1"
  open_file: "1.1.1"
  image_cropper: "1.0.0"
  # bmap_core_fluttify: 0.0.2+954ed74
  # flutter_2d_amap:
  #   git:
  #     url: https://github.com/simplezhli/flutter_2d_amap.git
  # amap_core_fluttify: "0.0.6"
  # amap_map_fluttify: "0.2.3+61475ac"
  # amap_location_fluttify: "0.2.1+38df15a"
  # amap_search_fluttify: "0.2.4+38df15a"
  # fluwx: "^1.1.1"
  # amap_base: 
  #   git:
  #     url: https://github.com/yohom/amap_base_flutter.git
  #     ref: develop
  #     path: base
  # amap_base_map: 0.4.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
      - assets/images/avatar_default.png
      - assets/images/duck.png
      - assets/images/slogan.png
      - assets/images/yacai.png
      - assets/images/logo.png
      - assets/images/bottom.png
      - assets/images/s-bottom.png
      - assets/images/title.png
      - assets/images/eye.png
      - assets/images/resume.png
      - assets/images/record.png
      - assets/images/setting.png
      - assets/images/msg.png
      - assets/images/msg_active.png
      - assets/images/mine.png
      - assets/images/mine_active.png
      - assets/images/full.png
      - assets/images/full_active.png
      - assets/images/parttime.png
      - assets/images/parttime_active.png
      - assets/images/practice.png
      - assets/images/practice_active.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
     - family: fontello
       fonts:
         - asset: assets/fonts/fontello.ttf
     - family: fangzheng
       fonts:
         - asset: assets/fonts/fangzheng.ttf
     - family: Dosis
       fonts:
         - asset: assets/fonts/Dosis/Dosis-Regular.ttf
           weight: 400
         - asset: assets/fonts/Dosis/Dosis-Medium.ttf
           weight: 500
         - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Dosis/Dosis-Bold.ttf
           weight: 800
         - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
           weight: 900